# render.yaml
databases: # Add this whole section
  - name: seo-tool-db
    region: frankfurt
    plan: free

services:
  - type: web # This is your main API service
    name: seo-tool-api
    env: node
    region: frankfurt # Use the same region as your database
    rootDir: ./backend
    plan: free
    buildFilter:
      paths:
        - backend/**
    buildCommand: "npm install && npx puppeteer browsers install chrome"
    startCommand: "npm start"
    healthCheckPath: /health # Add a simple /health endpoint to your API for this
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: seo-tool-db # This now correctly refers to the DB defined above
          property: connectionString
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
        # Force redeploy on August 31, 2025