# render.yaml
services:
  - type: web # This is your main API service
    name: seo-tool-api
    env: node
    region: frankfurt # Use the same region as your database
    rootDir: ./backend
    plan: free # Start on the free plan
    buildFilter:
      paths:
      - backend/**
    buildCommand: "npm install && npx puppeteer browsers install chrome"
    startCommand: "npm start"
    healthCheckPath: /api/health # Add a simple /health endpoint to your API for this
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: seo-tool-db # Must match the DB name from Step 1
          property: connectionString # <- The fix is here
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable